#!/bin/sh

###############################################################################################
#      * used to compile the source code of the firmware for the uC/PC.                	      # 
#                                                                  			      #
#      Sample Usage:                                                  			      #
#        $ compile PC|uC r                                                		      #
###############################################################################################


if [ $1 = uC ]; then
    avr-gcc -O1 -mmcu=atmega16 -o main.elf main.c
    avr-objcopy -j .text -O ihex main.elf main.hex
elif [ $1 = PC ]; then
    make CFLAGS=-DFOR_PC=1
elif [ $1 = clean ]; then
    rm -f -$2 *.[oa]
    rm -f -$2 *.hex *.elf *.srec *.map
fi


